using System;
using System.Collections.Generic;
using System.Text;

namespace Alons_Compiler
{
	// Iv reveiwed which characters ill be required to represent the Json data.
    enum SyntaxKind
	{
        LetterToken,
		NumberToken,
		WhitespaceToken,
		EndOfFileToken,
		BadToken,
		QuotationToken,
		ComaToken,
		ColonToken,
		OpenCurlyToken,
		CloseCurlyToken,
		OpenSquareToken,
		CloseSquareToken,
		AtToken,
		PlusToken,
		MinusToken
	}

	class SyntaxToken
	{
		// Constructor galore. I remember you said you didnt like this setup. But until you tell me why i will just do it like this.
		public SyntaxToken(SyntaxKind kind, int position, string text, object value)
		{
			Kind = kind;
			Position = position;
			Text = text;
			Value = value;
		}

		// These get statements were recommended / generated by VS. They seem to make the constructor NOT give me an error.
		public SyntaxKind Kind { get; }
		public int Position { get; }
		public string Text { get; }
		public object Value { get; }
	}
}
